### ISSUE TITLE
Syntax error while running kibiter for the first time

### ISSUE THREAD

**Issue by snack0verflow** [grimoirelab/kibiter#123]
**Kibana version**:
kibiter-6.1.4-4-linux-x86_64
**Elasticsearch version**:
elasticsearch-7.6.0
**Server OS version**:
elementary OS Hera 5.1 based on on Ubuntu 18.04
**Browser version**:

**Browser OS version**:

**Original install method (e.g. download page, yum, from source, etc.)**:
tar -xzf
**Description of the problem including expected versus actual behavior**:
Trying to run kibiter gives syntax error
**Steps to reproduce**:
 1. Install kibiter
 2. Try to run ./bin/kibana

**Errors in browser console (if relevant)**:
~/kibiter-6.1.4-4-linux-x86_64$ ./bin/kibana
/home/abid/kibiter-6.1.4-4-linux-x86_64/src/utils/streams/reduce_stream.js:40
    async transform(chunk, enc, callback) {
          ^^^^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/abid/kibiter-6.1.4-4-linux-x86_64/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
**Provide logs and/or server output (if relevant)**:

**Comment by vchrombie** [comment]
Hi @snack0verflow 

I think it is because of the version mismatch. You can read more about it from [here](https://github.com/chaoss/grimoirelab-kibiter#version-compatibility-with-elasticsearch).

**Comment by snack0verflow** [comment]
Hey @vchrombie,
This was while running kibiter alone without elasticsearch. The executable `bin/kibana` gave this syntax error.

**Comment by valeriocos** [comment]
A similar issue has been reported at https://github.com/chaoss/grimoirelab/issues/261. I didn't have time to have a deep look at it. @snack0verflow @vchrombie feel free to dive into it.

Thanks!
