### ISSUE TITLE
[kibiter 5.6 + ROR] Internal server error when creating a new index pattern

### ISSUE THREAD

**Issue by acs** [grimoirelab/kibiter#34]
Create a new Kibiter 5.6+ES 5.6 with ROR plugin active

`(acs@dellx) ~ $ docker-compose -f  ~/devel/GrimoireELK/docker/compose/bidek-56-lite.yml up -d 
`
Add some data to the ES:

`(acs@dellx) (master *$% u=) ~/devel/GrimoireELK/utils $ ./p2o.py -g -e http://bitergia:bitergia@localhost:9200 --enrich --index git git https://github.com/grimoirelab/perceval
`

Go to Kibiter at: http://localhost:5601 and try to create an index pattern for git_enrich. It will show you an Internal server error in the web page. The error in the web page is not useful at all, but taking a look to kibana logs:

```
(acs@dellx) (master *$% u=) ~/devel/GrimoireELK/utils $ docker logs --tail 10 -f compose_kibiter_1
{"type":"response","@timestamp":"2017-09-27T15:23:04Z","tags":[],"pid":1,"method":"get","statusCode":404,"req":{"url":"/api/index_patterns/_fields_for_wildcard?pattern=git_en&meta_fields=_source&meta_fields=_id&meta_fields=_type&meta_fields=_index&meta_fields=_score","method":"get","headers":{"host":"localhost:5601","connection":"keep-alive","accept":"application/json, text/plain, */*","kbn-version":"5.6.0-SNAPSHOT","user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/61.0.3163.79 Chrome/61.0.3163.79 Safari/537.36","referer":"http://localhost:5601/app/kibana","accept-encoding":"gzip, deflate, br","accept-language":"es,en-US;q=0.8,en;q=0.6"},"remoteAddress":"172.17.0.1","userAgent":"172.17.0.1","referer":"http://localhost:5601/app/kibana"},"res":{"statusCode":404,"responseTime":11,"contentLength":9},"message":"GET /api/index_patterns/_fields_for_wildcard?pattern=git_en&meta_fields=_source&meta_fields=_id&meta_fields=_type&meta_fields=_index&meta_fields=_score 404 11ms - 9.0B"}
{"type":"response","@timestamp":"2017-09-27T15:23:05Z","tags":[],"pid":1,"method":"get","statusCode":404,"req":{"url":"/api/index_patterns/_fields_for_wildcard?pattern=git_enri&meta_fields=_source&meta_fields=_id&meta_fields=_type&meta_fields=_index&meta_fields=_score","method":"get","headers":{"host":"localhost:5601","connection":"keep-alive","accept":"application/json, text/plain, */*","kbn-version":"5.6.0-SNAPSHOT","user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/61.0.3163.79 Chrome/61.0.3163.79 Safari/537.36","referer":"http://localhost:5601/app/kibana","accept-encoding":"gzip, deflate, br","accept-language":"es,en-US;q=0.8,en;q=0.6"},"remoteAddress":"172.17.0.1","userAgent":"172.17.0.1","referer":"http://localhost:5601/app/kibana"},"res":{"statusCode":404,"responseTime":11,"contentLength":9},"message":"GET /api/index_patterns/_fields_for_wildcard?pattern=git_enri&meta_fields=_source&meta_fields=_id&meta_fields=_type&meta_fields=_index&meta_fields=_score 404 11ms - 9.0B"}
{"type":"error","@timestamp":"2017-09-27T15:23:06Z","tags":[],"pid":1,"level":"error","message":"Cannot provide statusCode or message with boom error","error":{"message":"Cannot provide statusCode or message with boom error","name":"Error","stack":"Error: Cannot provide statusCode or message with boom error\n    at Object.exports.assert (/opt/kibana/node_modules/hoek/lib/index.js:736:11)\n    at Object.exports.wrap (/opt/kibana/node_modules/boom/lib/index.js:96:10)\n    at convertEsError (/opt/kibana/src/server/index_patterns/service/lib/errors.js:67:25)\n    at /opt/kibana/src/server/index_patterns/service/lib/es_api.js:63:40\n    at throw (native)\n    at step (/opt/kibana/src/server/index_patterns/service/lib/es_api.js:74:191)\n    at /opt/kibana/src/server/index_patterns/service/lib/es_api.js:74:402"},"url":{"protocol":null,"slashes":null,"auth":null,"host":null,"port":null,"hostname":null,"hash":null,"search":"?pattern=git_enrich&meta_fields=%5B%22_source%22%2C%22_id%22%2C%22_type%22%2C%22_index%22%2C%22_score%22%5D","query":{"pattern":"git_enrich","meta_fields":"[\"_source\",\"_id\",\"_type\",\"_index\",\"_score\"]"},"pathname":"/api/index_patterns/_fields_for_wildcard","path":"/api/index_patterns/_fields_for_wildcard?pattern=git_enrich&meta_fields=%5B%22_source%22%2C%22_id%22%2C%22_type%22%2C%22_index%22%2C%22_score%22%5D","href":"/api/index_patterns/_fields_for_wildcard?pattern=git_enrich&meta_fields=%5B%22_source%22%2C%22_id%22%2C%22_type%22%2C%22_index%22%2C%22_score%22%5D"}}
{"type":"response","@timestamp":"2017-09-27T15:23:06Z","tags":[],"pid":1,"method":"get","statusCode":500,"req":{"url":"/api/index_patterns/_fields_for_wildcard?pattern=git_enrich&meta_fields=_source&meta_fields=_id&meta_fields=_type&meta_fields=_index&meta_fields=_score","method":"get","headers":{"host":"localhost:5601","connection":"keep-alive","accept":"application/json, text/plain, */*","kbn-version":"5.6.0-SNAPSHOT","user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/61.0.3163.79 Chrome/61.0.3163.79 Safari/537.36","referer":"http://localhost:5601/app/kibana","accept-encoding":"gzip, deflate, br","accept-language":"es,en-US;q=0.8,en;q=0.6"},"remoteAddress":"172.17.0.1","userAgent":"172.17.0.1","referer":"http://localhost:5601/app/kibana"},"res":{"statusCode":500,"responseTime":16,"contentLength":9},"message":"GET /api/index_patterns/_fields_for_wildcard?pattern=git_enrich&meta_fields=_source&meta_fields=_id&meta_fields=_type&meta_fields=_index&meta_fields=_score 500 16ms - 9.0B"}
```

Some queries are getting a 404 (forbidden from Kibana server), and finally a 500 code is returned.

Creating an index pattern for the git raw index works smoothly. The logs are:

`{"type":"response","@timestamp":"2017-09-27T15:26:19Z","tags":[],"pid":1,"method":"get","statusCode":200,"req":{"url":"/api/index_patterns/_fields_for_wildcard?pattern=git&meta_fields=_source&meta_fields=_id&meta_fields=_type&meta_fields=_index&meta_fields=_score","method":"get","headers":{"host":"localhost:5601","connection":"keep-alive","accept":"application/json, text/plain, */*","kbn-version":"5.6.0-SNAPSHOT","user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/61.0.3163.79 Chrome/61.0.3163.79 Safari/537.36","referer":"http://localhost:5601/app/kibana","accept-encoding":"gzip, deflate, br","accept-language":"es,en-US;q=0.8,en;q=0.6"},"remoteAddress":"172.17.0.1","userAgent":"172.17.0.1","referer":"http://localhost:5601/app/kibana"},"res":{"statusCode":200,"responseTime":16,"contentLength":9},"message":"GET /api/index_patterns/_fields_for_wildcard?pattern=git&meta_fields=_source&meta_fields=_id&meta_fields=_type&meta_fields=_index&meta_fields=_score 200 16ms - 9.0B"}
`

**Comment by acs** [comment]
After some more testing, it seems that the bug is related with the name of the index. If the enriched index is called "git" it works. So maybe in ROR rules we have some rule related to the name of the index. @dlumbrer are you aware of that?

**Comment by acs** [comment]
The rules for ROR are at:

https://github.com/Bitergia/elasticsearch/blob/5.6.0/docker/elasticsearch.yml

but I can not see any rule that blocks to bitergia user the access to ES data.

**Comment by acs** [comment]
In ES logs I can not see any issues:

`(acs@dellx) ~/devel $ docker logs compose_elasticsearch_1
`

All the queries appear as accepted.

**Comment by acs** [comment]
After sync with @dlumbrer the problem is related with the permissions given in Bitergia Elasticsearch docker image. I think we can change them to a more open configuration to avoid this kind of errors. I am going to prepare a PR to it and generate a new elasticsearch BItergia docker image.

**Comment by acs** [comment]
Fixed with https://github.com/Bitergia/elasticsearch/pull/1
