### ISSUE TITLE
Kibiter crashes due to JS syntax error

### ISSUE THREAD

**Issue by canasdiaz** [grimoirelab/kibiter#40]
**Kibana version**: 5.1.1

**Elasticsearch version**: 5.1.1

**Server OS version**: NA

**Browser version**: Chromium 60.0.3112.78

**Browser OS version**: NA

**Original install method (e.g. download page, yum, from source, etc.)**: NA

**Description of the problem including expected versus actual behavior**: Kibiter does not server any content but an Internal Server Error

**Steps to reproduce**:
 1. Go to Kibiter's URL
 2. Look at your screen

**Provide logs and/or server output (if relevant)**:
```
{  
   "type":"error",
   "@timestamp":"2017-11-15T13:13:41Z",
   "tags":[  

   ],
   "pid":1,
   "level":"error",
   "message":"/opt/kibana/src/ui/views/chrome.jade:12\n    10|     meta(http-equiv='X-UA-Compatible', content='IE=edge,chrome=1')\n    11|     meta(name='viewport', content='width=device-width')\n  > 12|     meta(name='description', content='Bitergia analytics for 'Mozilla' provided by Bitergia using GrimoireLab Open Source technology')\n    13|     title Bitergia Analytics\n    14|     style.\n    15|       @font-face {\n\nUnexpected identifier",
   "error":{  
      "message":"/opt/kibana/src/ui/views/chrome.jade:12\n    10|     meta(http-equiv='X-UA-Compatible', content='IE=edge,chrome=1')\n    11|     meta(name='viewport', content='width=device-width')\n  > 12|     meta(name='description', content='Bitergia analytics for 'Mozilla' provided by Bitergia using GrimoireLab Open Source technology')\n    13|     title Bitergia Analytics\n    14|     style.\n    15|       @font-face {\n\nUnexpected identifier",
      "name":"SyntaxError",
      "stack":"SyntaxError: /opt/kibana/src/ui/views/chrome.jade:12\n    10|     meta(http-equiv='X-UA-Compatible', content='IE=edge,chrome=1')\n    11|     meta(name='viewport', content='width=device-width')\n  > 12|     meta(name='description', content='Bitergia analytics for 'Mozilla' provided by Bitergia using GrimoireLab Open Source technology')\n    13|     title Bitergia Analytics\n    14|     style.\n    15|       @font-face {\n\nUnexpected identifier\n    at assertExpression (/opt/kibana/node_modules/jade/lib/lexer.js:30:3)\n    at Object.attrs (/opt/kibana/node_modules/jade/lib/lexer.js:676:20)\n    at Object.next (/opt/kibana/node_modules/jade/lib/lexer.js:939:15)\n    at Object.lookahead (/opt/kibana/node_modules/jade/lib/lexer.js:113:46)\n    at Parser.lookahead (/opt/kibana/node_modules/jade/lib/parser.js:102:23)\n    at Parser.peek (/opt/kibana/node_modules/jade/lib/parser.js:79:17)\n    at Parser.tag (/opt/kibana/node_modules/jade/lib/parser.js:773:22)\n    at Parser.parseTag (/opt/kibana/node_modules/jade/lib/parser.js:759:17)\n    at Parser.parseExpr (/opt/kibana/node_modules/jade/lib/parser.js:211:21)\n    at Parser.block (/opt/kibana/node_modules/jade/lib/parser.js:729:25)\n    at Parser.tag (/opt/kibana/node_modules/jade/lib/parser.js:838:24)\n    at Parser.parseTag (/opt/kibana/node_modules/jade/lib/parser.js:759:17)\n    at Parser.parseExpr (/opt/kibana/node_modules/jade/lib/parser.js:211:21)\n    at Parser.block (/opt/kibana/node_modules/jade/lib/parser.js:729:25)\n    at Parser.tag (/opt/kibana/node_modules/jade/lib/parser.js:838:24)\n    at Parser.parseTag (/opt/kibana/node_modules/jade/lib/parser.js:759:17)"
   },
   "url":{  
      "protocol":null,
      "slashes":null,
      "auth":null,
      "host":null,
      "port":null,
      "hostname":null,
      "hash":null,
      "search":"",
      "query":{  

      },
      "pathname":"/app/kibana",
      "path":"/app/kibana",
      "href":"/app/kibana"
   }
}

```

**Comment by dlumbrer** [comment]
There is a problem with the single quotes ( ' )

I'm going to fix it

**Comment by canasdiaz** [comment]
Hey @dlumbrer, the current string it is not very well written. Instead of :+1: 
- 'Bitergia analytics for My Project provided by Bitergia using GrimoireLab Open Source technology'
I would use:
- 'Bitergia Analytics for My Project powered by GrimoireLab Open Source technology'

**Comment by dlumbrer** [comment]
Hi @sanacl,

I didn't choose that string. I agree with you but we have to discuss that change with @jsmanrique.

**Comment by jsmanrique** [comment]
Or even more simple:
'Bitergia Analytics for {{Project}}, powered by GrimoireLab technology'

**Comment by dlumbrer** [comment]
@jsmanrique, Understood!

I have already talked with @sanacl, I'm going to change it and make the PR!

**Comment by dlumbrer** [comment]
The new image of kibiter is already built in docker-hub!!
